[project]
name = "pyrandcracker"
version = "0.1.0"
description = "a better random cracker can predict python random lib number"
readme = "README.md"
requires-python = ">=3.5"
dependencies = [
    "numpy>=2.2.4",
]
